extends SceneTree


func _initialize() -> void:
	call_deferred("run_test")


func run_test() -> void:
	var state = root.get_node_or_null("GameState")
	if state == null:
		state = load("res://scripts/game_state.gd").new()
		state.name = "GameState"
		root.add_child(state)
	state.save_path = "user://smoke_test_save.cfg"
	state.reset()
	var packed: PackedScene = load("res://scenes/main.tscn")
	var game = packed.instantiate()
	root.add_child(game)
	await process_frame

	assert(game.splash_layer.visible)
	game.show_title()
	assert(game.title_panel.visible)
	game.show_office()
	await process_frame
	var hub_rect: Rect2 = game.hub_panel.get_global_rect()
	assert(hub_rect.end.x <= game.get_viewport_rect().end.x)
	assert(hub_rect.end.y <= game.get_viewport_rect().end.y)
	game.show_city_map()
	assert(game.map_panel.visible)
	game.show_contracts()
	assert(game.contracts_panel.visible)
	game.show_office()
	game.open_pause_menu()
	assert(game.pause_layer.visible)
	assert(paused)
	game.open_settings("pause")
	assert(game.settings_layer.visible)
	game.volume_slider.set_value_no_signal(65)
	game.music_slider.set_value_no_signal(40)
	game.sfx_slider.set_value_no_signal(60)
	game.text_speed_slider.set_value_no_signal(80)
	game.fullscreen_toggle.set_pressed_no_signal(false)
	game.save_and_close_settings()
	assert(state.master_volume == 65)
	assert(state.music_volume == 40)
	assert(state.sfx_volume == 60)
	assert(state.text_speed == 80)
	assert(game.pause_layer.visible)
	game.resume_game()
	assert(not paused)
	game.request_main_menu()
	assert(game.confirm_layer.visible)
	game.close_confirmation()
	game.request_exit_game()
	assert(game.confirm_layer.visible)
	game.close_confirmation()
	game.start_company_intro()
	assert(state.tutorial_seen)
	assert(game.dialogue_panel.visible)
	for index in range(10):
		game.advance_dialogue()
	assert(game.hub_panel.visible)

	game.start_first_job()
	assert(game.portrait_rect.visible)
	assert(game.portrait_rect.texture != null)
	for hero in ["Бруно", "Лика", "Топа", "Искра"]:
		for emotion in ["neutral", "happy", "worried", "determined"]:
			game.update_portrait(hero, emotion)
			assert(game.portrait_rect.texture != null)
	for emotion in ["neutral", "happy", "worried", "determined"]:
		game.update_portrait("Госпожа Тортилла", emotion)
		assert(game.portrait_rect.texture != null)
	for index in range(10):
		game.advance_dialogue()
	await process_frame
	assert(not game.portrait_rect.visible)

	for key in ["floor", "crack", "wiring", "grinder"]:
		var button: Button = game.hotspots_layer.get_node(key)
		game.inspect_hotspot(key, button)
		assert(button.modulate.a == 1.0)
		assert(button.text.begins_with("✓"))
	assert(game.inspected.size() == 4)
	assert(not game.inspection_continue.disabled)

	game.show_plan_choices()
	await process_frame
	assert(game.dialogue_choices.get_child_count() == 3)
	var last_choice: Control = game.dialogue_choices.get_child(2)
	assert(last_choice.get_global_rect().end.y <= game.get_viewport_rect().end.y)
	game.choose_plan("smart")
	for index in range(4):
		game.advance_dialogue()
	game.choose_grinder("restore")
	for index in range(4):
		game.advance_dialogue()
	await process_frame
	assert(game.puzzle_panel.visible)
	game.puzzle_panel.visible = false
	game.finish_job()

	assert(state.completed_projects == 1)
	assert(state.cafe_completed)
	assert(state.money == 1700)
	assert(state.quality == 2)
	assert(state.creativity == 3)
	assert(state.care == 2)
	assert(state.experience == 40)
	assert(game.result_panel.visible)

	game.show_contracts()
	game.start_kite_job()
	assert(game.portrait_rect.texture != null)
	game.update_portrait("Руди", "happy")
	assert(game.portrait_rect.texture != null)
	game.begin_kite_inspection()
	for key in ["skylight", "stairs", "beam", "cords"]:
		var kite_button: Button = game.hotspots_layer.get_node(key)
		game.inspect_hotspot(key, kite_button)
	assert(game.inspected.size() == 4)
	game.show_plan_choices()
	game.choose_kite_plan("smart")
	game.choose_kite_keepsake("display")
	game.finish_kite_job()
	assert(state.completed_projects == 2)
	assert(state.kite_workshop_completed)
	assert(state.money == 2380)
	assert(state.quality == 4)
	assert(state.creativity == 7)
	assert(state.care == 4)
	assert(state.experience == 95)
	var money_after_two_projects: int = state.money
	game.finish_kite_job()
	assert(state.money == money_after_two_projects)
	assert(state.completed_projects == 2)
	game.show_hero_skills()
	assert(game.skills_panel.visible)
	assert(state.available_skill_points() == 1)
	game.unlock_hero_skill("bruno", "Переговоры")
	assert(state.bruno_skill)
	assert(state.available_skill_points() == 0)

	game.show_upgrades()
	assert(game.upgrades_panel.visible)
	game.buy_upgrade("tools", 300, "Инструменты")
	game.buy_upgrade("design", 350, "Дизайн")
	game.buy_upgrade("client", 300, "Клиенты")
	assert(state.tools_level == 1)
	assert(state.design_level == 1)
	assert(state.client_level == 1)
	assert(state.money == 1430)
	game.buy_cottage()
	assert(state.cottage_owned)
	assert(state.money == 530)
	game.begin_cottage_inspection()
	for key in ["cottage_floor", "cottage_roof", "fireplace", "arched_window"]:
		var cottage_button: Button = game.hotspots_layer.get_node(key)
		game.inspect_hotspot(key, cottage_button)
	game.show_plan_choices()
	game.choose_cottage_plan("smart")
	game.choose_fireplace("restore")
	game.finish_cottage_flip()
	assert(state.cottage_completed)
	assert(not state.cottage_owned)
	assert(state.completed_projects == 3)
	assert(state.money == 2400)
	assert(state.quality == 7)
	assert(state.creativity == 10)
	assert(state.care == 7)
	assert(state.experience == 165)
	game.unlock_hero_skill("lika", "Дизайн")
	game.unlock_hero_skill("topa", "Прочность")
	assert(state.lika_skill)
	assert(state.topa_skill)
	game.show_city_map()
	assert(not game.garden_button.disabled)
	game.start_greenhouse_job()
	game.update_portrait("Мира", "happy")
	assert(game.portrait_rect.texture != null)
	game.begin_greenhouse_inspection()
	for key in ["glass", "support", "water_tank"]:
		var greenhouse_button: Button = game.hotspots_layer.get_node(key)
		game.inspect_hotspot(key, greenhouse_button)
	assert(game.inspected.size() == 3)
	game.show_plan_choices()
	game.choose_greenhouse_plan("smart")
	game.choose_vine("preserve")
	game.finish_greenhouse_job()
	assert(state.greenhouse_completed)
	assert(state.completed_projects == 4)
	assert(state.money == 3310)
	assert(state.quality == 11)
	assert(state.creativity == 15)
	assert(state.care == 11)
	assert(state.experience == 250)
	game.unlock_hero_skill("iskra", "Бережная технология")
	assert(state.iskra_skill)
	var money_after_greenhouse: int = state.money
	game.finish_greenhouse_job()
	assert(state.money == money_after_greenhouse)
	assert(state.completed_projects == 4)
	game.show_city_map()
	assert(not game.hill_button.disabled)
	game.start_observatory_job()
	game.update_portrait("Профессор Филин", "determined")
	assert(game.portrait_rect.texture != null)
	game.begin_observatory_inspection()
	for key in ["dome", "rotation_track", "telescope", "control"]:
		var observatory_button: Button = game.hotspots_layer.get_node(key)
		game.inspect_hotspot(key, observatory_button)
	game.show_plan_choices()
	game.choose_observatory_plan("smart")
	game.choose_telescope("restore")
	game.finish_observatory_job()
	assert(state.observatory_completed)
	assert(state.completed_projects == 5)
	assert(state.money == 4585)
	assert(state.quality == 15)
	assert(state.creativity == 20)
	assert(state.care == 15)
	assert(state.experience == 360)
	game.show_portfolio()
	assert(game.portfolio_panel.visible)
	game.start_finale()
	for index in range(14):
		game.advance_dialogue()
	assert(state.finale_seen)
	assert(game.credits_panel.visible)
	assert(game.company_ending_title() != "")
	game.show_office()
	var money_after_observatory: int = state.money
	game.finish_observatory_job()
	assert(state.money == money_after_observatory)
	assert(state.completed_projects == 5)

	state.reset()
	game.selected_plan = "quick"
	game.grinder_choice = "sell"
	game.finish_job()
	assert(state.money == 2070)
	assert(state.quality == -1)
	assert(state.creativity == 0)
	assert(state.care == -1)
	assert(state.cafe_completed)

	state.reset()
	assert(state.can_draw_event())
	state.current_event = "supplier_discount"
	game.selected_plan = "quick"
	game.grinder_choice = "restore"
	game.finish_job()
	assert(state.money == 1900)
	assert(state.current_event == "none")
	assert(state.cafe_completed)
	state.reset()
	state.save_settings(80, 45, false, 55, 75)
	print("SMOKE TEST PASSED: intro, full campaign, hero skills, random events, finale, credits and replay protection")
	quit(0)
